#!/usr/bin/env python3

import os
from build_config import *

def UpdateService(path_service):
    print("< -- Обновление {0} -- >".format(path_service))

    path_start = os.getcwd()

    #Проверяем существование исходников
    if os.path.isdir(path_service) == False:
        print("Не найден " + path_service)
        return

    #Переходим в директорию с исходниками
    os.chdir(path_service)

    #Обновление
    if os.system("git pull") != 0:
        print("Не удалось обновить сервис {0}!".format(path_service))
        return

    #Пермещаямся в начальную директорию
    os.chdir(path_start)

UpdateService(MAIN_SERIVCE)

#Обновление сервисов
for path_service, params_service in SERVICES.items():
    UpdateService(path_service)
